kind: ConfigMap
apiVersion: v1
metadata:
  name: fms-orchestr8-config-nlp
data:
  config.yaml: |
    chunkers:
      sentence:
        type: sentence
        service:
            hostname: "chunker-service.gorch-test.svc.cluster.local"
            port: 8085
    chat_generation:
      service:
        hostname: phi3-predictor.gorch-test.svc.cluster.local
        port: 8080
    detectors:
      regex_competitor:
        type: text_contents
        service:
            hostname: "127.0.0.1"
            port: 8080
        chunker_id: sentence
        default_threshold: 0.5
      hap:
        type: text_contents
        service:
          hostname: guardrails-detector-ibm-hap-predictor.gorch-test.svc.cluster.local
          port: 8000
        chunker_id: sentence
        default_threshold: 0.5